import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import NextThemeProvider from "@/lib/providers";
import { MSWComponent } from "@/app/_component/MSXComponent";
import AuthSession from "@/app/_component/AuthSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWComponent />
        <AuthSession>
          <StyledComponentsRegistry>
            <NextThemeProvider>{children}</NextThemeProvider>
          </StyledComponentsRegistry>
        </AuthSession>
      </body>
    </html>
  );
}
